# Generated by Django 4.0.4 on 2022-05-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('donate', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=100)),
                ('fname', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
