# Generated by Django 4.0.4 on 2022-05-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_rename_country_details_don_rename_donate_details_phn_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='Datas',
        ),
    ]
